### ISSUE TITLE
Clicking "Formatting Enabled" gives error in build IU-242.23339.11

### ISSUE THREAD

**Issue by sabob** [orangain/pretty-json-log-plugin#71]
Thanks for awesome plugin.

After I upgraded to Build #IU-242.23339.11, built on September 25, 2024

I get error notification
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.github.orangain.prettyjsonlog.action.ToggleEnabledAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.github.orangain.prettyjsonlog]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

The plugin mostly works though. The error appears when I open context menu and click "formatting enabled"

**Comment by orangain** [comment]
@sabob Thank you for reporting the issue! I was able to reproduce the issue in my environment. I will fix it as soon as possible.

**Comment by orangain** [comment]
@sabob I have just released the new version 0.4.1 of the plugin. That version will be available in JetBrains marketplace in a few days. Thanks for reporting the issue!

**Comment by sabob** [comment]
Great news. Thanks very much :)
